name: Build package

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  prettier:
    name: Check code formatting with prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run prettier linter
        run: npm run checkformat

  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build artifacts
        run: npm run build

      - name: Check for token nesting level errors
        run: ./bin/check_token_nesting.py

      - name: Store build artifact
        uses: actions/upload-artifact@v3
        with:
          name: package-lib
          path: lib/
          retention-days: 1

  publish:
    name: Publish the NPM package
    runs-on: ubuntu-latest
    needs:
      - build
      - prettier

    # do not publish in forks or non-tag pushes
    # prettier-ignore
    if: startsWith(github.ref, 'refs/tags/') && github.repository_owner == 'sergei-maertens'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: package-lib
          path: lib/

      - name: Publish package to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
